#!/bin/bash
# Author: https://github.com/cOb4l7
# Description: Simple Script To Brute-Force 7z Archive passwords e.g HackTheBox
#              Lightweight Machine.

# Variables
STATUS="" 
WORDLIST=""

help(){
echo "Usage: $0 <7z_file> <wordlist>"
exit 0
}

# If no arguments or just 1 show help message
if [[ $# -eq 0 ]] || [[ $# -eq 1 ]];then
        help
fi

if [[ $# -eq 2 ]];then
        # Check all the supplied user inputs to be correct
        if [[ "$1" = *.7z ]] && [[ -f $2 ]];then
                WORDLIST="$2"
                for password in $(cat "$WORDLIST")
                do
                        echo -en "\rTrying  $password"
                        7z x -p"$password" "$1" -aoa &> /dev/null
                        STATUS=$?
                        
                        if [[ $STATUS -eq 0 ]];then
                                echo -e "\rArchive password is: \"$password\""
                                break
                        fi
                done

        fi
fi
