#!/bin/bash
# Author:  https://github.com/mohabaks
# Description: Simple script to brute-force openssl enc with a known password

KEY="tarot"
while IFS= read -r cipher;
do
        openssl enc -d -"$cipher" -in salary_dec2003.csv.enc -out salary_dec2003.csv -k "$KEY"
        if [[ $? -eq 0 ]];then
                echo -e "+\033[32m Successfully decrypted the file with cipher: \033[31m $cipher\033[0m"
                exit
        fi
done < ciphers.txt
